language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install: npm install
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "5f27fbccace9"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"
dist: trusty
sudo: false
